ULTRASONIC_TRIGGER = 14
ULTRASONIC_ECHO = 15

MOTOR_LEFT_FORWARD = 24
MOTOR_LEFT_REVERSE = 23
MOTOR_LEFT_PWM = 25

MOTOR_RIGHT_FORWARD = 17
MOTOR_RIGHT_REVERSE = 27
MOTOR_RIGHT_PWM = 22

SERVO_PAN = 18
BUMP_SW = 7
